
#ifndef GUARD_CONSTANTS_BATTLE_PARTNERS_H
#define GUARD_CONSTANTS_BATTLE_PARTNERS_H

#define PARTNER_NONE                0
#define PARTNER_ORION_GRASS         1
#define PARTNER_ORION_FIRE          2
#define PARTNER_ORION_WATER         3

#endif  // GUARD_CONSTANTS_BATTLE_PARTNERS_H
